
prune_ratios:
  module.layer1.0.conv1.weight:
    0.75
  module.layer1.0.conv2.weight:
    0.75
  module.layer1.1.conv1.weight:
    0.75
  module.layer1.1.conv2.weight:
    0.75
  module.layer2.0.conv1.weight:
    0.75
  module.layer2.0.conv2.weight:
    0.75
  module.layer2.1.conv1.weight:
    0.75
  module.layer2.1.conv2.weight:
    0.75
  module.layer3.0.conv1.weight:
    0.75
  module.layer3.0.conv2.weight:
    0.75
  module.layer3.1.conv1.weight:
    0.75
  module.layer3.1.conv2.weight:
    0.75
  module.layer4.0.conv1.weight:
    0.75
  module.layer4.0.conv2.weight:
    0.75
  module.layer4.1.conv1.weight:
    0.75
  module.layer4.1.conv2.weight:
    0.75

