
prune_ratios:
  basic_model.layer1.0.conv1.weight:
    0.875
  basic_model.layer1.0.conv2.weight:
    0.875
  basic_model.layer1.1.conv1.weight:
    0.875
  basic_model.layer1.1.conv2.weight:
    0.875
  basic_model.layer2.0.conv1.weight:
    0.875
  basic_model.layer2.0.conv2.weight:
    0.875
  basic_model.layer2.1.conv1.weight:
    0.875
  basic_model.layer2.1.conv2.weight:
    0.875
  basic_model.layer3.0.conv1.weight:
    0.875
  basic_model.layer3.0.conv2.weight:
    0.875
  basic_model.layer3.1.conv1.weight:
    0.875
  basic_model.layer3.1.conv2.weight:
    0.875
  basic_model.layer4.0.conv1.weight:
    0.875
  basic_model.layer4.0.conv2.weight:
    0.875
  basic_model.layer4.1.conv1.weight:
    0.875
  basic_model.layer4.1.conv2.weight:
    0.875

